services:
 - mysql

before_install:
 - mysql -e 'CREATE DATABASE transposer COLLATE utf8_general_ci'
 - mysql transposer < song_data.sql

language: 
 - php

php:
 - '7.1'

before_script: 
 - composer install

script: 
 - phpunit
 - php tests/testAllTranspositions.php
