<?php

use App\Http\Controllers\WebManifestController;
use App\Http\Middleware\NeedsLoginMiddleware;
use Illuminate\Support\Facades\Route;
use App\Http\Middleware\NeedsLogin;

Route::get('/', [\NeoTransposer\Controllers\Index::class, 'get']);

//SEO-friendly URLs for books
$bookUrls = [
    1 => '/nyimbo-njia-neokatekumenato',
    2 => '/cantos-camino-neocatecumenal',
    3 => '/songs-neocatechumenal-way',
    4 => '/cantos-caminho-neocatecumenal',
    5 => '/canti-cammino-neocatecumenale',
];

foreach ($bookUrls as $bookId => $slug) {
    Route::get($slug, [\App\Http\Controllers\BookController::class, 'get'])->defaults('bookId', $bookId)->name('book_' . $bookId);
}

$validLocales = '(' . implode('|', array_keys(config('nt.languages'))) . ')';

Route::prefix('{locale}')
    ->where(['locale' => $validLocales])
    ->middleware([\App\Http\Middleware\SetLocaleFromUrl::class])
    ->group(function () {

        // Login routes
        Route::get('/login', [\App\Http\Controllers\LoginController::class, 'get'])->name('login');
        Route::post('/login', [\App\Http\Controllers\LoginController::class, 'post']);

        Route::get('/manifest.json', [WebManifestController::class, 'get'])->name('webmanifest');

        Route::get('/people-compatible-transpositions',  function() { return 'Stub'; })
            ->name('people-compatible-info');

        Route::group(['middleware' => NeedsLoginMiddleware::class], function () {

            //Route::get('/user/voice', [\App\Http\Controllers\UserVoiceController::class, 'get'])
            Route::get('/user/voice', function() { return 'Stub'; })
                ->name('user_voice');

            Route::get('/user/book', [\App\Http\Controllers\UserBookController::class, 'get'])
                ->name('user_book');

            //Route::get('/all-songs-report', [\App\Http\Controllers\AllSongsReportController::class, 'get'])
            Route::get('/all-songs-report', function() { return 'Stub'; })
                ->name('all_songs_report');

            //Route::get('/{_locale}/wizard', [\App\Http\Controllers\WizardSelectStandardController::class, 'showPage'])
            Route::get('/wizard', function() { return 'Stub'; })
                ->name('wizard_step1');
        });
    });

Route::group(['middleware' => NeedsLoginMiddleware::class], function() {

    Route::get('/set-user-data', [\App\Http\Controllers\SetUserDataController::class, 'get'])
        ->name('set_user_data');
});

// Feedback route handles auth check itself (returns 408 for AJAX when session expires)
Route::post('/feedback', [\App\Http\Controllers\ReceiveFeedbackController::class, 'post'])
    ->name('transposition_feedback');

Route::get('/transpose/{id_song}', [\App\Http\Controllers\TransposeSongController::class, 'get'])
    ->name('transpose_song');


/** Begin generated by ChatGPT */

/*
// Sitemap route
Route::get('/sitemap.xml', [\App\Http\Controllers\SitemapController::class, 'get']);




Route::get('/{_locale}/wizard/select-standard', [\App\Http\Controllers\WizardSelectStandardController::class, 'selectStandardAndShowInstructionsPage'])
    ->where('_locale', $validLocales)
    ->name('wizard_select_standard')
    ->middleware(NeedsLogin::class);

// Wizard Empiric routes
Route::match(['get', 'post'], '/{_locale}/wizard/lowest', [\App\Http\Controllers\WizardEmpiricController::class, 'lowest'])
    ->where('_locale', $validLocales)
    ->name('wizard_empiric_lowest')
    ->middleware(NeedsLogin::class);

Route::match(['get', 'post'], '/{_locale}/wizard/highest', [\App\Http\Controllers\WizardEmpiricController::class, 'highest'])
    ->where('_locale', $validLocales)
    ->name('wizard_empiric_highest')
    ->middleware(NeedsLogin::class);


// External Login Finish route
Route::get('/{_locale}/external-login-finish', [\App\Http\Controllers\LoginController::class, 'externalLoginFinish'])
    ->where('_locale', $validLocales)
    ->name('external_login_finish')
    ->middleware(NeedsLogin::class);

// Admin routes
Route::get('/admin/insert-song', [\App\Http\Controllers\InsertSongController::class, 'get']);
Route::post('/admin/insert-song', [\App\Http\Controllers\InsertSongController::class, 'post']);
Route::get('/admin/dashboard', [\App\Http\Controllers\AdminDashboardController::class, 'get']);
Route::get('/admin/chord-correction', [\App\Http\Controllers\ChordCorrectionPanelController::class, 'get']);
Route::post('/admin/chord-correction', [\App\Http\Controllers\ChordCorrectionPanelController::class, 'post'])
    ->name('chord_correction_panel');

// Serve CSS route
Route::get('/static/compiled-' . config('neoconfig.css_cache') . '.css', [\App\Http\Controllers\ServeCssController::class, 'get']);

//Easter eggs ;-)
Route::get('/get-lucky', [\App\Http\Controllers\TransposeSongController::class, 'get'])
    ->defaults('id_song', 118);

Route::get('/sura-yako', [\App\Http\Controllers\TransposeSongController::class, 'get'])
    ->defaults('id_song', 319);

// Manifesto page route
Route::get('/{_locale}/manifesto', function ($_locale) {
    return view('pages.manifesto.' . $_locale, [
        'page_title' => __('Manifesto')
    ]);
})->where('_locale', 'es')
    ->name('manifesto');

// People-compatible transpositions route
Route::get('/{_locale}/people-compatible-transpositions', function ($_locale) {
    $templateFile = 'pages.people-compatible-info.' . $_locale;

    if (!view()->exists($templateFile)) {
        $templateFile = 'pages.people-compatible-info.en';
    }

    return view($templateFile, [
        'page_title' => __('People-compatible transpositions')
    ]);
})->where('_locale', $validLocales)
    ->name('people-compatible-info');

*/
